### ISSUE TITLE
TV-App UI 设计讨论

### ISSUE THREAD

**Issue by rocky225** [ObsessionPlace/dev4tv-hybrid-app#1]
TV界面显示UI
1.显示Merge ID(选择ID最大值)
2.显示Tower @XXX
3.显示Issue ID
4.显示MileStone
5.显示类似bearychat信息

![edu4tvuidesign](https://cloud.githubusercontent.com/assets/2193909/11734947/aebc2d3a-9ff6-11e5-9ea2-1959004ae47c.PNG)

**Comment by karlsun** [comment]
今天一姐碰到的问题，看能否将jenkins的构建检测倒计时显示出来

**Comment by karlsun** [comment]
@rocky225 这样的waterline格式的信息可以做成某一块内容

**Comment by rocky225** [comment]
@karlsun 这个是否要写jenkins-scripts呢

**Comment by karlsun** [comment]
@rocky225 先研究jenkins有哪些API可以用，尽量不去在jenkins上加东西吧。

**Comment by rocky225** [comment]
jenkins提供了REST API可以调用获取信息,持续时间好像也有,之前看了一下bearychat的推送功能,需要插件

**Comment by karlsun** [comment]
![image](https://cloud.githubusercontent.com/assets/1631926/11894958/aa91d4ca-a5b5-11e5-92e3-cd550eee26d7.png)

**Comment by rocky225** [comment]
@karlsun 这种显示会不会太小了,如果不会,像这种复杂的设计也是可行的

**Comment by karlsun** [comment]
@rocky225 实际显示是TV的屏幕大小，我们可以做不同的视图类型及组织方式，方便的显示在不同的屏上

**Comment by rocky225** [comment]
@karlsun 这样也是可以的,在设计上就要多放些心思了,不同设备显示的重点不一样,然后还要定出3-4种支持的分辨率

**Comment by karlsun** [comment]
@rocky225 觉得这个东西的定位，有点偏向于最终解决方案了，脱离了开源组件的初衷，得思考下是否关闭此任务，重新找方向
